analitica/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.core import views
from django.contrib.auth import views as auth_views
from apps.personas import views as persona_views

from apps.personas.views import CustomPasswordResetView, CustomPasswordResetDoneView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.personas.urls')),
    path('',include('apps.core.urls')),

    #COBERTURA
    



    
  

    

    path('grafica', views.grafica, name="grafica"),
  
    
    path('administrador/', views.administrador, name="administrador"),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('validacion_email/', persona_views.validacion_email, name='validacion_email'),
    path('validar_documento/', persona_views.validar_documento, name='validar_documento'),
    

]

apps/core/urls.py
from django.urls import path
from apps.core import views as core_views


app_name = 'cores'
urlpatterns = [
 
    path('cobertura/index', core_views.cobertura, name="cobertura"),
    path('cobertura_mapa/', core_views.Cobertura_mapa.as_view(), name='cobertura_mapa'),
    path('programa/index', core_views.Programa_index, name="programa_index"),
    path('programa/', core_views.Programa.as_view(), name='programa'),
    path('ficha/<int:identificador_ficha>/', core_views.detalle_ficha, name='detalle_ficha'),
    path('desercion', core_views.Desercion.as_view(), name="Desercion"),
    path('formacion_regular/index', core_views.Formacion_regular_index, name='formacion_regular_index'),
    path('metas/create/', core_views.Meta_create.as_view(), name="meta_create"),
    path('metas_formacion/create/', core_views.Meta_formacion_create.as_view(), name="meta_formacion_create"),
    path('estrategias_institucionales/index/', core_views.Estrategias_institucionales_index, name='estrategias_institucionales_index'),
    path('estrategias/create/', core_views.Estrategias_create.as_view(), name='estrategias_create'),
    path('estrategias/est_total_meta/<int:met_id>/', core_views.get_meta_valores, name='est_total_meta'),
    path('meta_estrategia_detalle/create', core_views.Meta_estrategia_detalle.as_view(), name="meta_estrategia_detalle"),
    path('get_estrategia_data/<int:id_estd_modalidad>/', core_views.get_estrategia_data, name='get_estrategia_data'),
    path('meta_data/<int:id_estd_meta>/', core_views.meta_data, name='meta_data'),
    path('meta_detalle/<int:estd_meta>/', core_views.meta_detalle, name='meta_detalle'),
    path('filtrar_datos_y_modalidades/',core_views.metas_formacion_filtros.as_view(), name='filtrar_datos_y_modalidades'),
    path('filtrar_estrategias_institucionales/',core_views.estrategias_institucionales_filtros.as_view(), name='filtrar_estrategias_institucionales'),
    path('get_meta/<int:meta_id>/', core_views.get_meta, name='get_meta'),
    #MODALIDAD
    path('modalidad/index/', core_views.Modalidad_index, name='modalidad_index'),
    path('modalidad/create/', core_views.Modalidad_create.as_view(), name='modalidad_create'),
    path('modalidad/delete/<int:pk>', core_views.Modalidad_delete.as_view(), name='modalidad_delete'),
    path('modalidad/edit/<int:pk>', core_views.Modalidad_edit.as_view(), name='modalidad_edit'),
    
    #ROLES
    path('asignacion_roles/', core_views.Asignacion_roles, name="asignacion_roles" ),
    
    #GRAFICAS GENERAL
    path('general/index', core_views.general, name="general"),
    
    #estrategias institucionales graficas 
    path('estrategias/index', core_views.estrategias, name="estrategias_index"),
    #ALERTAS
    path('verificar-año/', core_views.Verificar_año, name='verificar_año'),
    #verificaciones de formularios meta formacion 
    path('verificacion_meta_formacion_regular/', core_views.Verificacion_meta_formacion_regular, name="verificacion_meta_formacion_regular"),
    
    #eliminar y editar meta formacion (formacion regular)
    path('meta_formacion/delete/<int:pk>', core_views.Meta_formacion_delete.as_view(), name="verificacion_meta_formacion_regular"),
    path('meta_formacion/edit/<int:pk>', core_views.Meta_formacion_edit.as_view(), name="meta_formacion_regular_edit"),
    #eliminar y editar estrategias institucionales (estrategia)
    path('estrategia_institucional/delete/<int:pk>', core_views.estrategia_institucional_delete.as_view(), name='estrategia_institucional_delete'),
    path('estrategia_institucional/edit/<int:pk>', core_views.estrategia_institucional_edit.as_view(), name='estrategia_institucional_edit'),
    #eliminar y editar  meta estrategia (estrategias institucionales)

    path('meta_estrategias_intitucionales/delete/<int:pk>', core_views.meta_estrategias_intitucionales_delete.as_view(), name='meta_estrategias_intitucionales_delete'),
    path('meta_estrategias_intitucionales/edit/<int:pk>', core_views.meta_estrategias_intitucionales_edit.as_view(), name='meta_estrategias_intitucionales_edit'),
    
    #eliminar y editar  meta estrategia (estrategias institucionales)
    path('meta/edit/<int:pk>', core_views.meta_edit.as_view(), name='meta_edit'),
    path('meta/delete/<int:pk>', core_views.meta_delete.as_view(), name='meta_delete'),
    path('meta/index/', core_views.meta_index, name='meta_index'),
    
    #BILINGUISMO
    path('bilinguismo/index/', core_views.Bilinguismo_index, name='bilinguismo_index'),
    path('bilinguismo/create/', core_views.Bilinguismo_create.as_view(), name='bilinguismo_create'),
    path('bilinguismo/delete/<int:pk>', core_views.Bilinguismo_delete.as_view(), name='bilinguismo_delete'),
    path('bilinguismo/edit/<int:pk>', core_views.Bilinguismo_edit.as_view(), name='bilinguismo_edit'),
    #CENTRO_DE_FORMACION
    path('centro_de_formacion/index/', core_views.Centro_de_formacion_index, name='centro_de_formacion_index'),
    path('centro_de_formacion/create/', core_views.Centro_de_formacion_create.as_view(), name='centro_de_formacion_create'),
    path('centro_de_formacion/delete/<int:pk>', core_views.Centro_de_formacion_delete.as_view(), name='centro_de_formacion_delete'),
    path('centro_de_formacion/edit/<int:pk>', core_views.Centro_de_formacion_edit.as_view(), name='centro_de_formacion_edit'),
    #REGIONAL
    path('regional/index/', core_views.Regional_index, name='regional_index'),
    path('regional/create/', core_views.Regional_create.as_view(), name='regional_create'),
    path('regional/delete/<int:pk>', core_views.Regional_delete.as_view(), name='regional_delete'),
    path('regional/edit/<int:pk>', core_views.Regional_edit.as_view(), name='regional_edit'),
    
    #NIVEL FORMACION
    path('nivel_formacion/index/', core_views.Nivel_formacion_index, name='nivel_formacion_index'),
    path('nivel_formacion/create/', core_views.Nivel_formacion_create.as_view(), name='nivel_formacion_create'),
    path('nivel_formacion/delete/<int:pk>', core_views.Nivel_formacion_delete.as_view(), name='nivel_formacion_delete'),
    path('nivel_formacion/edit/<int:pk>', core_views.Nivel_formacion_edit.as_view(), name='nivel_formacion_edit'),
    


]   

templates/Centro_de_formacion/centro_de_formacion.html
{% extends 'home.html' %}

{% block contenido %}
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap/css/administrador.css' %}">
<div class="main p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="text-center">
                    <h1 class="h1 mb-4">Centro de formación</h1>
                </div>
                <div class="mt-4">

                    <button type="button" class="btn btn-success btn-sm mr-2" data-toggle="modal" data-target="#crearModal">Agregar</button>

                    
                    <table class="table table-striped">
                        <thead>
                            <tr>
                             
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                             
                                <th scope="col">Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for centro_de_formacions in  centro_de_formacion%}
                            <tr>
                                
                          
                                
                                <th scope="row">{{centro_de_formacions.id}}</th>
                                <td>{{centro_de_formacions.centro_de_formacion}}</td>
                    
                                
                                <td>
                                    <button type="button" class="btn btn-warning btn-sm mr-2" data-toggle="modal" data-target="#editarModal" data-id="{{centro_de_formacions.id}}" data-centro="{{centro_de_formacions.centro_de_formacion}}"  onclick="Editar_bilinguismo(this)">Editar</button>
                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#eliminarModal"  data-id="{{centro_de_formacions.id}}" onclick="Delete_centro_de_formacion(this)">Eliminar</button>
                                </td>
                            </tr>
                            {%endfor%}
                            
                         
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


  
    <div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true"data-backdrop="static">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editarModalLabel">Editar Bilinguismo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
            
                    <form id="editarForm" method="post">
                        <div class="form-group">
                            {% csrf_token %}
                         
                       
                            <div class="mb-3">
                                <label for="" class="form-label">Centro de formación</label>
                                {{ form_centro_de_formacion.centro_de_formacion}}
                            </div>
                            
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </form>
            </div>
        </div>
    </div>

    <!-- Contenedor para los modales -->
    <div class="modal-container">
        <div class="modal fade" id="crearModal" tabindex="-1" role="dialog" aria-labelledby="crearModalLabel" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="crearModalLabel">Crear Centro de formacion</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                
                        <form  action="{% url 'cores:centro_de_formacion_create' %}" method="post">
                            <div class="form-group">
                                {% csrf_token %}
                                {{ form_centro_de_formacion.as_p }}
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
        
        <!-- Modal Eliminar -->
        <div class="modal fade" id="eliminarModal" tabindex="-1" role="dialog" aria-labelledby="eliminarModalLabel" aria-hidden="true"data-backdrop="static">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="eliminarModalLabel">Eliminar centro de formación</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Estás seguro de que quieres eliminar este centro de formación?</p>
                    </div>
                    <div class="modal-footer">
                        <form id="deleteForm" method="post">
                            {% csrf_token%}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.modal-container {
    position: relative;
    margin: auto;
    margin-top: 10%;
    max-width: 600px;
}
.modal-container .modal {
    position: fixed;
    top: 10%;
    left: 50%;
    transform: translateX(-50%);
    width: 80%;
    max-width: 600px;
    z-index: 1050;
    overflow-x: hidden;
    overflow-y: auto;
    outline: 0;
}
</style>
<script>
    function Delete_centro_de_formacion(button) {
        const pk = button.getAttribute('data-id');
        document.getElementById('deleteForm').action = `/centro_de_formacion/delete/${pk}`;
    }

 
    function Editar_bilinguismo(button){
        const pk = button.getAttribute('data-id');
        const id_centro_de_formacion = button.getAttribute('data-centro')
   
   
        document.getElementById('editarForm').action = `/centro_de_formacion/edit/${pk}`;
        document.getElementById('id_centro_de_formacion').value = id_centro_de_formacion
 
       
    }
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock contenido %}