analitica/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.core import views
from django.contrib.auth import views as auth_views
from apps.personas import views as persona_views

from apps.personas.views import CustomPasswordResetView, CustomPasswordResetDoneView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.personas.urls')),
    path('',include('apps.core.urls')),

    #COBERTURA
    



    
  

    

    path('grafica', views.grafica, name="grafica"),
  
    
    path('administrador/', views.administrador, name="administrador"),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('validacion_email/', persona_views.validacion_email, name='validacion_email'),
    path('validar_documento/', persona_views.validar_documento, name='validar_documento'),
    

]

apps/core/urls.py
from django.urls import path
from apps.core import views as core_views


app_name = 'cores'
urlpatterns = [
 
    path('cobertura/index', core_views.cobertura, name="cobertura"),
    path('cobertura_mapa/', core_views.Cobertura_mapa.as_view(), name='cobertura_mapa'),
    path('programa/index', core_views.Programa_index, name="programa_index"),
    path('programa/', core_views.Programa.as_view(), name='programa'),
    path('ficha/<int:identificador_ficha>/', core_views.detalle_ficha, name='detalle_ficha'),
    path('desercion', core_views.Desercion.as_view(), name="Desercion"),
    path('formacion_regular/index', core_views.Formacion_regular_index, name='formacion_regular_index'),
    path('metas/create/', core_views.Meta_create.as_view(), name="meta_create"),
    path('metas_formacion/create/', core_views.Meta_formacion_create.as_view(), name="meta_formacion_create"),
    path('estrategias_institucionales/index/', core_views.Estrategias_institucionales_index, name='estrategias_institucionales_index'),
    path('estrategias/create/', core_views.Estrategias_create.as_view(), name='estrategias_create'),
    path('estrategias/est_total_meta/<int:met_id>/', core_views.get_meta_valores, name='est_total_meta'),
    path('meta_estrategia_detalle/create', core_views.Meta_estrategia_detalle.as_view(), name="meta_estrategia_detalle"),
    path('get_estrategia_data/<int:id_estd_modalidad>/', core_views.get_estrategia_data, name='get_estrategia_data'),
    path('meta_data/<int:id_estd_meta>/', core_views.meta_data, name='meta_data'),
    path('meta_detalle/<int:estd_meta>/', core_views.meta_detalle, name='meta_detalle'),
    path('filtrar_datos_y_modalidades/',core_views.metas_formacion_filtros.as_view(), name='filtrar_datos_y_modalidades'),
    path('filtrar_estrategias_institucionales/',core_views.estrategias_institucionales_filtros.as_view(), name='filtrar_estrategias_institucionales'),
    path('get_meta/<int:meta_id>/', core_views.get_meta, name='get_meta'),
    #MODALIDAD
    path('modalidad/index/', core_views.Modalidad_index, name='modalidad_index'),
    path('modalidad/create/', core_views.Modalidad_create.as_view(), name='modalidad_create'),
    path('modalidad/delete/<int:pk>', core_views.Modalidad_delete.as_view(), name='modalidad_delete'),
    path('modalidad/edit/<int:pk>', core_views.Modalidad_edit.as_view(), name='modalidad_edit'),
    
    #ROLES
    path('asignacion_roles/', core_views.Asignacion_roles, name="asignacion_roles" ),
    
    #GRAFICAS GENERAL
    path('general/index', core_views.general, name="general"),
    
    #estrategias institucionales graficas 
    path('estrategias/index', core_views.estrategias, name="estrategias_index"),
    #ALERTAS
    path('verificar-año/', core_views.Verificar_año, name='verificar_año'),
    #verificaciones de formularios meta formacion 
    path('verificacion_meta_formacion_regular/', core_views.Verificacion_meta_formacion_regular, name="verificacion_meta_formacion_regular"),
    
    #eliminar y editar meta formacion (formacion regular)
    path('meta_formacion/delete/<int:pk>', core_views.Meta_formacion_delete.as_view(), name="verificacion_meta_formacion_regular"),
    path('meta_formacion/edit/<int:pk>', core_views.Meta_formacion_edit.as_view(), name="meta_formacion_regular_edit"),
    #eliminar y editar estrategias institucionales (estrategia)
    path('estrategia_institucional/delete/<int:pk>', core_views.estrategia_institucional_delete.as_view(), name='estrategia_institucional_delete'),
    path('estrategia_institucional/edit/<int:pk>', core_views.estrategia_institucional_edit.as_view(), name='estrategia_institucional_edit'),
    #eliminar y editar  meta estrategia (estrategias institucionales)

    path('meta_estrategias_intitucionales/delete/<int:pk>', core_views.meta_estrategias_intitucionales_delete.as_view(), name='meta_estrategias_intitucionales_delete'),
    path('meta_estrategias_intitucionales/edit/<int:pk>', core_views.meta_estrategias_intitucionales_edit.as_view(), name='meta_estrategias_intitucionales_edit'),
    
    #eliminar y editar  meta estrategia (estrategias institucionales)
    path('meta/edit/<int:pk>', core_views.meta_edit.as_view(), name='meta_edit'),
    path('meta/delete/<int:pk>', core_views.meta_delete.as_view(), name='meta_delete'),
    path('meta/index/', core_views.meta_index, name='meta_index'),
    
    #BILINGUISMO
    path('bilinguismo/index/', core_views.Bilinguismo_index, name='bilinguismo_index'),
    path('bilinguismo/create/', core_views.Bilinguismo_create.as_view(), name='bilinguismo_create'),
    path('bilinguismo/delete/<int:pk>', core_views.Bilinguismo_delete.as_view(), name='bilinguismo_delete'),
    path('bilinguismo/edit/<int:pk>', core_views.Bilinguismo_edit.as_view(), name='bilinguismo_edit'),
    #CENTRO_DE_FORMACION
    path('centro_de_formacion/index/', core_views.Centro_de_formacion_index, name='centro_de_formacion_index'),
    path('centro_de_formacion/create/', core_views.Centro_de_formacion_create.as_view(), name='centro_de_formacion_create'),
    path('centro_de_formacion/delete/<int:pk>', core_views.Centro_de_formacion_delete.as_view(), name='centro_de_formacion_delete'),
    path('centro_de_formacion/edit/<int:pk>', core_views.Centro_de_formacion_edit.as_view(), name='centro_de_formacion_edit'),
    #REGIONAL
    path('regional/index/', core_views.Regional_index, name='regional_index'),
    path('regional/create/', core_views.Regional_create.as_view(), name='regional_create'),
    path('regional/delete/<int:pk>', core_views.Regional_delete.as_view(), name='regional_delete'),
    path('regional/edit/<int:pk>', core_views.Regional_edit.as_view(), name='regional_edit'),
    
    #NIVEL FORMACION
    path('nivel_formacion/index/', core_views.Nivel_formacion_index, name='nivel_formacion_index'),
    path('nivel_formacion/create/', core_views.Nivel_formacion_create.as_view(), name='nivel_formacion_create'),
    path('nivel_formacion/delete/<int:pk>', core_views.Nivel_formacion_delete.as_view(), name='nivel_formacion_delete'),
    path('nivel_formacion/edit/<int:pk>', core_views.Nivel_formacion_edit.as_view(), name='nivel_formacion_edit'),
    


]   

apps/personas/urls.py
from django.urls import path
from apps.personas.views import CustomPasswordChangeView
from apps.personas import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
app_name = 'personas'

urlpatterns = [
    path('registro/',views.Registro, name='registro'),
    path('inicio_sesion/', views.inicio_sesion, name='inicio_sesion'),
    path('cierre_sesion/', views.Cierre_sesion, name='cierre_sesion'),
    path('home/', views.Home, name='Home'),
    path('perfil/', views.Perfil, name="perfil"),
    path('editar_perfil/<int:per_documento>/', views.Editar_perfil, name="editar_perfil"),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    #archivos
    path('subir_P04/', views.subir_P04, name='subir_P04'),
    path('P04/', views.p04, name="P04"),
    path('upload/', views.Subir_poblacion_vulnerable, name='upload_excel'),
    path('poblacion_vulnerable/index/', views.Poblacion_vulnerable, name="poblacion_vulnerable"),
    path('poblacion_vulnerable_graficas/', views.Poblacion_vulnerable_graficas, name="poblacion_vulnerable_graficas"),
    #CRUD DE ROL
    path('roles/index/',views.Roles_index, name="roles_index"),
    path('roles/create/',views.Roles_create.as_view(), name="roles_create"),
    path('roles/delete/<int:pk>',views.Roles_delete.as_view(), name="roles_delete"),
    path('roles/edit/<int:pk>',views.Roles_edit.as_view(), name="roles_edit"),
    #CRUD DE PERMISO
    path('permisos/index/',views.Permisos_index, name="permisos_index"),
    path('permisos/create/',views.Permisos_create.as_view(), name="permisos_create"),
    path('permisos/delete/<int:pk>',views.Permisos_delete.as_view(), name="permisos_delete"),
    path('permisos/edit/<int:pk>',views.Permisos_edit.as_view(), name="permisos_edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/personas/forms.py
from django import forms
from .models import Persona
from .models import P04
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from apps.personas.models import Rol
from django.contrib.auth.models import Permission

#FORMS DE REGISTRO
class PersonaForm(UserCreationForm):
    
    email = forms.EmailField(required=True, label="Correo electrónico", max_length=50, help_text="Coloca tu correo electrónico", error_messages={'invalid': 'Solo puedes colocar caracteres válidos para el email'})
 
    
    class Meta:
        model = Persona
        fields = ['per_documento', 'per_tipo_documento', 'email', 'per_nombres', 'per_apellidos', 'per_telefono', 'password1', 'password2']
        Widget = {
            'per_tipo_documento': forms.Select(attrs={'class':'form-control'})
        }
        
    #validaciones
    def clean_per_correo(self):
        email = self.cleaned_data.get('email').lower()
        if Persona.objects.filter(email=email).exists():
            raise ValidationError("El correo electrónico ya ha sido tomado")
        return email
    

    
    def save(self, commit=True):
        user = super(PersonaForm, self).save(commit=False)
        user.per_correo = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    

#FORMS DE INICIO DE SESION
class LoginForm(forms.Form):
    per_documento = forms.IntegerField(label='Documento de identidad')
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    
    def clean_per_documento(self):
        per_documento = self.cleaned_data['per_documento']
        # No es necesario validar con isdigit() para un IntegerField
        return per_documento

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if len(password1) < 8 or not any(char.isdigit() for char in password1) or not any(char.isalpha() for char in password1):
            raise forms.ValidationError("La contraseña debe tener al menos 8 caracteres y contener números y letras.")
        return password1


#FORMS DE EDITAR PERFIL
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ('per_documento', 'per_tipo_documento', 'per_nombres', 'per_apellidos', 'email', 'per_telefono','per_image')
        Widget = {
            'per_tipo_documento': forms.Select(attrs={'class':'form-control'})
        }
        



class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField()


class Form_rol(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(queryset=Permission.objects.all().order_by('-id'), required=True, widget=forms.Select)
    class Meta:
        model = Rol
        fields = [
            'rol_nombre', 'rol_descripcion','permissions'
        ]
      
class Form_permissions(forms.ModelForm):
    class Meta:
        model = Permission
        fields = [
            'name','codename'
        ]
        # estableces el campo directamente a la hora de crearlo ene lepost 

templates/administrador.html
{% extends 'home.html' %}

{% block contenido %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/administrador.css' %}" />
  <div class="main p-3">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10">
          <div class="text-center">
            <h1 class="h1 mb-4">Listado de Usuarios</h1>
          </div>
          <div class="mt-4">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Email</th>
                  <th scope="col">Roles</th>
                  <th scope="col">Acciones</th>
                </tr>
              </thead>
              <tbody>
                {% for persona in personas %}
                  <tr>
                    <th scope="row">{{ persona.per_documento }}</th>
                    <td>{{ persona.per_nombres }} {{ persona.per_apellidos }}</td>
                    <td>{{ persona.email }}</td>
                    <td>
                        {% if persona.roles.exists %}
                        {% for rol in persona.roles.all %}
                            {{ rol.rol_nombre }}<br />
                        {% endfor %}
                    {% else %}
                        Sin rol asignado
                    {% endif %}
                    </td>
                    <td>
                        <form method="post" action="{% url 'cores:asignacion_roles' %}">
                            {% csrf_token %}
                            <input type="hidden" name="persona_id" value="{{ persona.per_documento }}" />
                            <select name="rol_id">
                                {% for rol in roles %}
                                    <option value="{{ rol.rol_id }}"
                                        {% if rol in persona.roles.all %}
                                            selected
                                        {% endif %}>
                                        {{ rol.rol_nombre }}
                                    </option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-primary btn-sm">Asignar Rol</button>
                        </form>
                    </td>
                    
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Asegúrate de incluir los scripts de Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sidebar With Bootstrap</title>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />

    {%load static%}
    <link rel="stylesheet" href="{% static 'bootstrap/css/home.css'%}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/navbar.css'%}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
   
</head>



<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'personas:Home'%}">Analitica</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                  
                  <img src="{{ request.user.per_image.url}}" alt="Foto de perfil" class="rounded-circle" style="width: 40px; height: 40px;">
             
                <span class="navbar-text">Bienvenido, <a href="{% url 'personas:perfil'%}">{{ request.user.per_nombres }}</a></span>
                {% endif %}
            </li>
        </ul>
        </ul>
    </nav>
    
<section class="contenedor ">

    <div class="wrapper">
        <aside id="sidebar">
            
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <img src="{% static 'bootstrap/img/menu.png' %}" alt="Protection Icon" style="width: 25px; height: 25px;">
                </button>
            </div>
            <ul class="sidebar-nav">
                {% if perms.can_view_admin_dashboard %}

                <li class="sidebar-item">
                    <a href="{% url 'administrador'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Usuario</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:modalidad_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Modalidad</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:bilinguismo_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Bilinguismo</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:centro_de_formacion_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Centro de formación</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:regional_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Regional</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:nivel_formacion_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Nivel formacion</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'cores:meta_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Gestionar Meta</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'personas:roles_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Roles</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.can_view_admin_dashboard %}
                <li class="sidebar-item">
                    <a href="{% url 'personas:permisos_index'%}" class="sidebar-link">
                        <img src="{% static 'bootstrap/img/usuario.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Permisos</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'cores:formacion_regular_index'%}" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#multi" aria-expanded="false" aria-controls="multi">
                    
                      
                        <img src="{% static 'bootstrap/img/meta.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">

                        <span>Metas</span>
                    </a>
                    <ul id="multi" class="sidebar-dropdown list-unstyled collapse" >
                        <li class="sidebar-item">
                            <a href="{% url 'cores:formacion_regular_index'%}" class="sidebar-link">Formacion Regular</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'cores:estrategias_institucionales_index'%}" class="sidebar-link">Estrategias Institucionales</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.can_view_reporteador_dashboard %}
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                       data-bs-target="#nuevo" aria-expanded="false" aria-controls="nuevo">
                        <img src="{% static 'bootstrap/img/carga-en-la-nube.png' %}" alt="Nuevo Icono" style="width: 20px; height: 20px;">
                        <span>Subir archivos</span>
                    </a>
                    <ul id="nuevo" class="sidebar-dropdown list-unstyled collapse">
                        <li class="sidebar-item">
                            <a href="{% url 'personas:poblacion_vulnerable'%}" class="sidebar-link">Poblacion vulnerable</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'personas:P04'%}" class="sidebar-link">P04</a>
                        </li>
                    </ul>
                </li>
                {% endif%}
             
                <li class="sidebar-item">
                    <a href="{% url 'cores:general'%}" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#auth" aria-expanded="false" aria-controls="auth">
                        <img src="{% static 'bootstrap/img/reporte.png' %}" alt="Protection Icon" style="width: 20px; height: 20px;">
                        <span>Reportes</span>
                    </a>
                    <ul id="auth" class="sidebar-dropdown list-unstyled collapse" >
                        <li class="sidebar-item">
                            <a href="{% url 'cores:general'%}" class="sidebar-link">General</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'cores:cobertura_mapa'%}" class="sidebar-link">Cobertura</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'cores:programa'%}" class="sidebar-link">Programa</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'cores:Desercion'%}" class="sidebar-link" >Desercion</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'cores:estrategias_index'%}" class="sidebar-link">Estrategias</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'personas:poblacion_vulnerable_graficas'%}" class="sidebar-link">Poblacion vulnerables</a>
                        </li>

                    </ul>
                </li>

               
               
                
                
         
            </ul>
            <div class="sidebar-footer">
                <a href="{% url 'personas:cierre_sesion'%}" class="sidebar-link">
                    <i><img src="{% static 'bootstrap/img/cerrar-sesion-icon.png' %}" alt="Protection Icon" style="    margin-left: -5px; width: 20px; height: 20px;"></i>
                    <span>Logout</span>
                </a>
            </div>
        </aside>
        {% block contenido%}


        
    
        {% endblock contenido%}
    </div>
        <script src="{% static 'bootstrap/js/home.js'%}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    </section>
</body>

</html>

templates/inicio_sesion.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/inicio_sesion.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Inicio_sesion</title>
</head>

<body>
    {% include 'nav_inicio.html' %}
    <section class="sesiones">
       
        <div class="form-boxes">
            <div class="form-value">
                {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% elif message.tags == 'success' %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-info" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
                <form action="{% url 'personas:inicio_sesion' %}" method="post" id="loginForm">
                    {% csrf_token %}
               
                    <h2 class="login_titulo">Inicio de sesión</h2>
                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                        <input type="text" name="per_documento" id="id_per_documento" required>
                        <label for="id_per_documento">Documento de identidad</label>
                        <span class="error-message" id="error_per_documento" style="display: none;">Este campo solo permite números.</span>
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        <input type="password" name="password1" id="id_password1" required>
                        <label for="id_password1">Contraseña</label>
                        <div class="error-container">
                            <span class="error-message" id="error_password1" style="display: none;">La contraseña debe tener al menos 8 caracteres y contener números y letras.</span>
                        </div>
                    </div>
                    <div class="container">
                        <button type="submit" class="boton_registro">Iniciar Sesión</button>
                    </div>
                    <div class="bottom-links">
                        <a class="contra" href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
                        <a href="{% url 'personas:registro' %}">Registrarse</a>
                    </div>
                </form>
            </div>
        </div>
    
     
 
    </section>

    <script>
        // Script para ocultar mensajes flash después de un tiempo
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(function() {
                var alerts = document.querySelectorAll('.alert');
                alerts.forEach(function(alert) {
                    alert.classList.add('fade');
                    setTimeout(function() {
                        alert.remove();
                    }, 600); // Tiempo para la animación de desvanecimiento
                });
            }, 5000); // Tiempo en milisegundos antes de ocultar el mensaje (5 segundos en este caso)
        });
    </script>

    <script src="{% static 'bootstrap/js/inicio_sesion.js'%}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>

templates/nav_inicio.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <a class="navbar-brand" href="{% url 'personas:inicio_sesion'%}">Analitica</a>

    
</nav>