analitica/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.core import views
from django.contrib.auth import views as auth_views
from apps.personas import views as persona_views

from apps.personas.views import CustomPasswordResetView, CustomPasswordResetDoneView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.personas.urls')),
    path('',include('apps.core.urls')),

    #COBERTURA
    



    
  

    

    path('grafica', views.grafica, name="grafica"),
  
    
    path('administrador/', views.administrador, name="administrador"),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('validacion_email/', persona_views.validacion_email, name='validacion_email'),
    path('validar_documento/', persona_views.validar_documento, name='validar_documento'),
    

]

apps/personas/urls.py
from django.urls import path
from apps.personas.views import CustomPasswordChangeView
from apps.personas import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
app_name = 'personas'

urlpatterns = [
    path('registro/',views.Registro, name='registro'),
    path('inicio_sesion/', views.inicio_sesion, name='inicio_sesion'),
    path('cierre_sesion/', views.Cierre_sesion, name='cierre_sesion'),
    path('home/', views.Home, name='Home'),
    path('perfil/', views.Perfil, name="perfil"),
    path('editar_perfil/<int:per_documento>/', views.Editar_perfil, name="editar_perfil"),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    #archivos
    path('subir_P04/', views.subir_P04, name='subir_P04'),
    path('P04/', views.p04, name="P04"),
    path('upload/', views.Subir_poblacion_vulnerable, name='upload_excel'),
    path('poblacion_vulnerable/index/', views.Poblacion_vulnerable, name="poblacion_vulnerable"),
    path('poblacion_vulnerable_graficas/', views.Poblacion_vulnerable_graficas, name="poblacion_vulnerable_graficas"),
    #CRUD DE ROL
    path('roles/index/',views.Roles_index, name="roles_index"),
    path('roles/create/',views.Roles_create.as_view(), name="roles_create"),
    path('roles/delete/<int:pk>',views.Roles_delete.as_view(), name="roles_delete"),
    path('roles/edit/<int:pk>',views.Roles_edit.as_view(), name="roles_edit"),
    #CRUD DE PERMISO
    path('permisos/index/',views.Permisos_index, name="permisos_index"),
    path('permisos/create/',views.Permisos_create.as_view(), name="permisos_create"),
    path('permisos/delete/<int:pk>',views.Permisos_delete.as_view(), name="permisos_delete"),
    path('permisos/edit/<int:pk>',views.Permisos_edit.as_view(), name="permisos_edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Permisos/permisos.html
{% extends 'home.html' %}

{% block contenido %}
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap/css/administrador.css' %}">
<div class="main p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="text-center">
                    <h1 class="h1 mb-4">Listado de Permisos</h1>
                </div>
                <div class="mt-4">

                    <button type="button" class="btn btn-success btn-sm mr-2" data-toggle="modal" data-target="#crearModal">Agregar</button>

                    
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Descripcion</th>
                                <th scope="col">Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for permiso in  permisos%}
                            <tr>
                                
                      
                                <th scope="row">{{permiso.id}}</th>
                                <td>{{permiso.name}}</td>
                                <td>{{permiso.codename}}</td>
                              
                                <td>
                                    <button type="button" class="btn btn-warning btn-sm mr-2" data-toggle="modal" data-target="#editarModal" data-id="{{permiso.rol_id}}" data-nombre="{{permiso.rol_nombre}}" data-descripcion="{{permiso.rol_descripcion}}"onclick="Editar_permiso(this)">Editar</button>
                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#eliminarModal"  data-id="{{permiso.rol_id}}" onclick="Delete_permiso(this)">Eliminar</button>
                                </td>
                            </tr>
                            {%endfor%}
                            
                        
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


  

    <!-- Contenedor para los modales -->
    <div class="modal-container">
        <div class="modal fade" id="crearModal" tabindex="-1" role="dialog" aria-labelledby="crearModalLabel" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="crearModalLabel">Crear modalidad</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                
                        <form  action="{% url 'personas:permisos_create' %}" method="post">
                            <div class="form-group">
                                {% csrf_token %}
                                {{ forms_permisos.as_p }}
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
        <div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true"data-backdrop="static">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editarModalLabel">Editar Rol</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                
                        <form id="editarForm" method="post">
                            <div class="form-group">
                                {% csrf_token %}
                                <label for="rol_nombre">Nombre:</label>
                                <input type="text" id="rol_nombre" name="rol_nombre" class="form-control" />
                                <label for="rol_descripcion">Nombre:</label>
                                <input type="text" id="rol_descripcion" name="rol_descripcion" class="form-control" />
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </div>
                </form>
                </div>
            </div>
        </div>

        <!-- Modal Eliminar -->
        <div class="modal fade" id="eliminarModal" tabindex="-1" role="dialog" aria-labelledby="eliminarModalLabel" aria-hidden="true"data-backdrop="static">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="eliminarModalLabel">Eliminar Usuario</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Estás seguro de que quieres eliminar este usuario?</p>
                    </div>
                    <div class="modal-footer">
                        <form id="deleteForm" method="post">
                            {% csrf_token%}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.modal-container {
    position: relative;
    margin: auto;
    margin-top: 10%;
    max-width: 600px;
}
.modal-container .modal {
    position: fixed;
    top: 10%;
    left: 50%;
    transform: translateX(-50%);
    width: 80%;
    max-width: 600px;
    z-index: 1050;
    overflow-x: hidden;
    overflow-y: auto;
    outline: 0;
}
</style>
<script>
    function Delete_permisos(button) {
        const pk = button.getAttribute('data-id');
        document.getElementById('deleteForm').action = `/permisos/delete/${pk}`;
    }
    function Editar_permisos(button){
        const pk = button.getAttribute('data-id');
        const rol = button.getAttribute('data-nombre')
        const rol_description = button.getAttribute('data-descripcion')
  
        document.getElementById('editarForm').action = `/permisos/edit/${pk}`;
        document.getElementById('rol_nombre').value = rol
        document.getElementById('rol_descripcion').value = rol_description
    }
</script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock contenido %}